quarkus.http.port=8081

validation.email.notblank=The library's email address cannot be empty.
validation.email.format=The email format provided is invalid.
validation.email.size=The email should be between 5 and 150 characters long.